name: Performance Test
description: Run performance tests using a custom script and Dockerized environment
author: Your Name

inputs:
  container_name:
    description: Name of the Docker container
    required: true
  url:
    description: URL of the application
    required: true

# runs:
#   using: "composite"
#   steps:
#     # Use the custom entrypoint script
#     - name: Run Performance Test
#       shell: bash
#       run: |
#         ./entrypoint.sh "${{ inputs.container_name }}" "${{ inputs.url }}"

runs:
  using: "docker"  # Use Docker for execution
  image: "./app.dockerfile"  # Specify that the Dockerfile in this directory should be built
  args:  # Pass inputs as arguments to the ENTRYPOINT script
    - ${{ inputs.container_name }}
    - ${{ inputs.url }}