name: 'Performance Test'
description: 'Run performance tests using JMeter'
inputs:
  image-tag:
    description: 'Docker image tag to test'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'