name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t my-python-app:${{ github.sha }} -f app.dockerfile .

      # Push Docker Image to DockerHub
      - name: Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
          docker tag my-python-app:${{ github.sha }} myrepo/my-python-app:${{ github.sha }}
          docker push myrepo/my-python-app:${{ github.sha }}

      # Perform Vulnerability Scanning with Trivy
      - name: Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: my-python-app:${{ github.sha }}

      # Run Performance Test
      - name: Run Performance Tests
        uses: ./.github/actions/performance-test/
        with:
          container_name: my-python-app-container
          url: http://localhost:8080