name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

env:
  IMAGE_NAME: flask-app
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} -f app.dockerfile .

      # Push Docker image
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      # Vulnerability scan with Trivy
      - name: Scan image for vulnerabilities
        uses: aquasecurity/trivy-action@v0.9.3
        with:
          image-ref: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      # Run performance tests using the custom action
      - name: Run performance tests
        uses: ./.github/actions/performance-test
        with:
          jmeter_test_file: '.github/actions/performance-test/test-plan.jmx'
